name: ML CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest

    - name: Run tests
      run: pytest test_classifier.py

    - name: Train model
      run: python model.py

    - name: Upload trained models
      uses: actions/upload-artifact@v4
      with:
        name: trained-models
        path: |
          model_cluster1.joblib
          model_cluster2.joblib
